language: java
sudo: required
jdk:
  - oraclejdk7
  - openjdk7
before_script:
  - sudo add-apt-repository -y ppa:fkrull/deadsnakes 
  - sudo apt-get -q update
  - sudo apt-get install python3.5 python-virtualenv 
  - virtualenv -p /usr/bin/python3.5 my-env
  - source my-env/bin/activate
  - ./gradlew installDist
  - ./gradlew installSlimDist
script: 
  - RUNNER=build/install/svparse-slim/bin/svparse
  - tests/runtests.py $RUNNER tests/parsertests/* --verbose
  - tests/runtests.py $RUNNER tests/lexertests/* --verbose
  - tests/runtests.py $RUNNER tests/regressiontests/* --verbose
  - tests/runtests.py $RUNNER tests/failsonwindows/* --verbose
  - tests/runtests.py $RUNNER tests/negative_tests/* --should fail --verbose
  - tests/runtests.py $RUNNER tests/knownfailures/* --should fail --verbose
